# Generated by Django 5.2.5 on 2025-08-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_profilwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriWO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri_wo/')),
                ('profil_wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='pengguna.profilwo')),
            ],
        ),
    ]
