# Generated by Django 5.2.5 on 2025-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0003_galeriwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilwo',
            name='foto_sampul',
            field=models.ImageField(blank=True, null=True, upload_to='sampul/'),
        ),
    ]
