# Generated by Django 5.2.5 on 2026-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0004_profilwo_foto_sampul'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilwo',
            name='kapasitas_harian',
            field=models.PositiveIntegerField(default=1, help_text='Berapa maksimal acara yang bisa tim Anda tangani dalam satu hari?', verbose_name='Kapasitas Acara per Hari'),
        ),
    ]
