# Generated by Django 5.2.5 on 2025-11-22 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gedung', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=255)),
                ('kapasitas', models.CharField(max_length=100)),
                ('harga_sewa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foto_gedung', models.ImageField(blank=True, null=True, upload_to='gedung_photos/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('kategori', models.CharField(choices=[('S', 'S (Small)'), ('M', 'M (Medium)'), ('L', 'L (Large)')], default='M', max_length=1)),
                ('fasilitas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gedung_wo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='paket_fotos/')),
                ('is_active', models.BooleanField(default=True)),
                ('kategori_gedung', models.CharField(choices=[('non_gedung', '❌ Tanpa Gedung / Venue Bebas'), ('S', '🏢 Gedung Small (S)'), ('M', '🏢 Gedung Medium (M)'), ('L', '🏢 Gedung Large (L)')], default='non_gedung', help_text='Tentukan apakah paket ini termasuk fasilitas gedung, dan kategori apa.', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_wo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPortofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri_paket/')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='organizer.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_acara', models.DateField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Konfirmasi'), ('dikonfirmasi', 'Dikonfirmasi'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=20)),
                ('tgl_pesan', models.DateTimeField(auto_now_add=True)),
                ('nama_pasangan', models.CharField(max_length=200, null=True)),
                ('telepon', models.CharField(max_length=20, null=True)),
                ('lokasi_acara', models.CharField(help_text='Diisi manual jika paket Tanpa Gedung', max_length=255, null=True)),
                ('jumlah_tamu', models.IntegerField(null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status_pembayaran', models.CharField(choices=[('belum_bayar', 'Belum Dibayar'), ('lunas', 'Lunas')], default='belum_bayar', max_length=20)),
                ('catatan_pembatalan', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gedung_dipilih', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan_gedung', to='organizer.gedung')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.paket')),
            ],
        ),
    ]
