# Generated by Django 5.2.5 on 2025-08-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paket',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='paket_fotos/'),
        ),
    ]
