# Generated by Django 5.2.5 on 2025-11-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Konfirmasi'), ('dikonfirmasi', 'Dikonfirmasi (Belum Bayar)'), ('disiapkan', 'Sedang Disiapkan'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=20),
        ),
    ]
