# Generated by Django 5.2.5 on 2025-12-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_pesanan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Konfirmasi'), ('dikonfirmasi', 'Dikonfirmasi'), ('disiapkan', 'Sedang Disiapkan'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=20),
        ),
    ]
