# Generated by Django 5.2.5 on 2025-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_paket_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='jumlah_tamu',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='lokasi_acara',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='nama_pasangan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='telepon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
