# Generated by Django 5.2.5 on 2025-12-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_alter_pesanan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGedung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='gedung_galeri/')),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri_gedung', to='organizer.gedung')),
            ],
        ),
    ]
