# Generated by Django 5.2.5 on 2025-08-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_pesanan_catatan_pesanan_jumlah_tamu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPortofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri_paket/')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='organizer.paket')),
            ],
        ),
    ]
