# Generated by Django 5.2.5 on 2025-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_fotoportofolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='catatan_pembatalan',
            field=models.TextField(blank=True, help_text='Alasan jika pesanan ditolak oleh WO', null=True),
        ),
    ]
