# Generated by Django 5.2.5 on 2025-12-24 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_fotogedung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('komentar', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penulis_ulasan', to=settings.AUTH_USER_MODEL)),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan_wo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
