# Generated by Django 5.2.5 on 2025-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_pesanan_catatan_pembatalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='status_pembayaran',
            field=models.CharField(choices=[('belum_bayar', 'Belum Dibayar'), ('lunas', 'Lunas')], default='belum_bayar', max_length=20),
        ),
    ]
