# Generated by Django 5.2.5 on 2025-12-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_ulasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulasan',
            name='pesanan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_ulasan', to='organizer.pesanan'),
        ),
    ]
