# Generated by Django 5.2.5 on 2026-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_ulasan_pesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gedung',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif'),
        ),
    ]
