# Generated by Django 5.2.5 on 2026-01-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_gedung_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='tgl_fitting',
            field=models.DateTimeField(blank=True, help_text='Jadwal fitting baju pengantin', null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='tgl_survey',
            field=models.DateTimeField(blank=True, help_text='Jadwal survey lokasi/gedung', null=True),
        ),
    ]
